export const TodoActionType = {
    ADD_ITEM: "ADD_ITEM",
    MOVE_TO_DONE:"MOVE_TO_DONE",
    MOVE_BACK: "MOVE_BACK",
    DELETE_FROM_TODO:"DELETE_FROM_TODO",
    DELETE_FROM_DONE:"DELETE_FROM_DONE",
}



