export const TodoActionType = {
    ADD_ITEM: "ADD_ITEM",
    MOVE_TO_DONE:"MOVE_TO_DONE",
    MOVE_BACK: "MOVE_BACK",
    DELETE_FROM_TODO:"DELETE_FROM_TODO",
    DELETE_FROM_DONE:"DELETE_FROM_DONE",
    FIRE_TIMER:"FIRE_TIMER",
    CHANGE_ITEM_STATE: "CHANGE_ITEM_STATE",
    POMO_DECREASE: "POMO_DECREASE",
    POMO_INCREASE: "POMO_INCREASE",
    CLEAR_ACHEIVEMENT: "CLEAR_ACHEIVEMENT",
    TODO_PAGE_UP:"TODO_PAGE_UP",
    TODO_PAGE_DOWN :"TODO_PAGE_DOWN"
}



